[project]
authors = ["nichmor <nmorkotilo@gmail.com>"]
channels = ["conda-forge"]
name = "py-arwen"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
develop = "PIP_REQUIRE_VIRTUALENV=false maturin develop"
build-release = "PIP_REQUIRE_VIRTUALENV=false maturin develop --release"

test = { cmd = "pytest", depends-on = ["develop"] }

fmt-python = "ruff format arwen tests"
fmt-rust = "cargo fmt --all"
lint-python = "ruff check ."
lint-rust = "cargo clippy --all"

lint = { depends-on = ["lint-python", "lint-rust"] }


# checks for the CI
fmt-rust-check = "cargo fmt --all --check"
fmt-python-check = "ruff format rattler examples tests --diff"
fmt-check = { depends-on = ["fmt-python-check", "fmt-rust-check"] }


[dependencies]
python = "3.9.*"
pip = "~=23.2.1"
maturin = "~=1.2.2"
pytest = "*"
ruff = ">=0.3.3,<0.4"
