site_name: "arwen - modern patching of binaries"
# site_url: https://prefix-dev.github.io/pixi

theme:
  name: material
  # custom_dir: docs/overrides
  # favicon: assets/pixi.png
  # logo: assets/pixi.png
  font:
    text: Red Hat Text
    code: JetBrains Mono

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: prefix-light
      accent: prefix-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: prefix
      accent: prefix
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    edit: material/pencil
    view: material/eye

  features:
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.code.annotate
    # - content.code.select Sponsor only
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.footer

# extra_css:
#   - stylesheets/extra.css

repo_url: https://github.com/nichmor/arwen/
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 3
      permalink: "#"
  - mdx_truly_sane_lists


nav:
  - Getting Started: index.md
  - Why patching binaries?: why_patch.md
  - Patching:
      - Introduction: patching/introduction.md
      - ELF: patching/elf.md
      - Macho: patching/macho.md
      - Patching an ELF file: patching/patching_elf.md
      - Patching an Macho file: patching/patching_macho.md

  - Reference:
      - CLI: reference/cli/arwen.md

plugins:
  - search
  - mike:
